[build]
  command = "gulp build"
  publish = "dist/"

[[redirects]]
  from = "/about"
  to = "/contact"
  status = 301
  force = true

[[redirects]]
  from = "/work/*"
  to = "/work/"
  status = 301
  force = true
